### PR TITLE
Added info about stack sizes in Factorio

### LINKED ISSUE #69: New stack sheet?
Add another cheat sheet with stack related things

* Stack table for all items: https://wiki.factorio.com/Stack
* Train cargo wagon stacks: 4 rows of 10 = 40
* Steel, iron wood chests
* Stacks per chest for cargo wagon

### PR DESCRIPTION
**Pull request by Mikrotherion**
Added stack size info.
Closes #69 (I hope).

### CODE REVIEW

**Comment by DDDGamer** [comment]
Oh wow, cool, can you provide screenshot(s), make sure you run `npm run build` and that it passes.

**Comment by Mikrotherion** [comment]
Hello,

here are 2 screenshots. NPM run build passes.

**Comment by DDDGamer** [comment]
@Mikrotherion I dont see the screenshots, no link or embed, did you reply via email or something? That wouldn't work, gotta do it on github itself.

**Comment by Mikrotherion** [comment]
Ah, yes, by E-Mail. Will post them later today.


Denis Zholob <notifications@github.com> schrieb am Mi., 24. Okt. 2018,
05:59:

**Comment by DDDGamer** [comment]
> OK... here come the screenshots:
> cheatsheet2
> cheatsheet1

Ok some fixes i'm thinking:
* Table should be centered (see the train colors sheet for example) 
* Wording in the beginning is redundant should be enhanced, I'm thinking something like
	- Factorio groups and stores identical items in [Stacks](https://wiki.factorio.com/Stack)
	- Different items have a different stack size
	- *Stack size:* Maximum items in one stack.
* In the Inserter Capacity Bonus page; link the "stack size" phrase in the description to this cheatcheet
	"Inserter capacity research is used to increase the stack size of the inserters."
* Groups some table items to shrink the table vertically:
	- silo, satellite
	- discharge, target, art shell
	- tank, car, fuel
	- steam, turbine, nuke plant
	- refinery, chem plant, beacon, lab
	- offshore pump, pumpjack
	- pipe ground, pump, storage tank
	- combinators, switch, speaker, lamp
	- heat ex, heat pipe, boiler, solar, accumulator
	- assembly machine, centrifuge, miners
	- ores, sulfur, explosives
	- engines, robot frames
	- shields, batteries
	- gates, radars, turrets
	- iron stick, gear, pipe, repair pack, rail
	- fish, wood
	- plastic, processing unit
* Post new screenshots for the work in this Pull Request (as opposed to the ticket)
* If you want you can add in the other part of the ticket otherwise i'll do it after we merge your code:
	- If you do this, no need to center the table as these tables would be on the other side (left, and main table on the right)
	- Table for stack slots for each container in game (all chests, wagon, car, tank, player etc..)
	- Maybe another table below that shows the (slots_per_chest = cargo_wagon_slots / chests) for 12, 6, 4 and 2 chests

**Comment by Mikrotherion** [comment]
Hi there,
sorry, been busy and will stay busy for a few days. I'll try to change it according to your suggestions.

**Pull request closed without merging**
