### PR TITLE
Belt troughput speeds for 0.17 (#96)

### PR DESCRIPTION
**Pull request by HonkingGoose**
Throughput is 15 for yellow, 30 for red, 45 for blue.
https://wiki.factorio.com/Tutorial:Cheat_sheet#Belt_throughput

### CODE REVIEW

**Comment by deniszholob** [comment]
Multiplier is fine
1x15=15
2x15=30
3x15=45
thats all it is, just say how fast the other tiers are compared to yellow

**Comment by HonkingGoose** [comment]
I noticed the multiplier is just the speedup compared to a yellow belt. So I'm leaving that alone, that hasn't changed.

**Comment by deniszholob** [comment]
Need to change the image caption from 7.11 to 8 though

**Comment by HonkingGoose** [comment]
Where do you keep the image captions? And where is the Transport Belt Density located?
I don't know where those things are on your repository. Still learning... :smile:

**Comment by deniszholob** [comment]
Thats cool, i'm sure is going to be a great learning opportunity

https://github.com/deniszholob/factorio-cheat-sheet/blob/master/src/app/views/cheat-sheets/belt-throughput/belt-throughput.component.html

**Comment by deniszholob** [comment]
Looks great thanks for changing this! :)

**Comment by HonkingGoose** [comment]
Cheers for merging them in. :+1: 

Cool, it seems that *deploy/netlify* shows my changes before you make them? Or does *deploy/netlify* only change when you take my commits and merge them?

**Comment by deniszholob** [comment]
It should show your changes in a preview deploy, that's how i reviewed your changes along with looking at the code changes

**Comment by HonkingGoose** [comment]
Wow that is really handy. :smile: Makes it a lot easier to check if I'm not accidentally messing up the webpage.

**Comment by deniszholob** [comment]
Indeed, but you should be running it locally when writing changes.
Maybe check out some tutorials on how Angular works?

But basically the command is `npm run start` assuming you have done `npm install` first and have Nodejs installed

**Comment by HonkingGoose** [comment]
Hmm, I should learn some git from the command line then, to work on the computer locally. That way I can also build the website myself and check my work before pushing it here.

I'll check out Angular and how to get setup with that.

**Comment by deniszholob** [comment]
Ah you are just editing them here in git?
I use https://www.sourcetreeapp.com/ so i don't even need to remember any git commands :p

**Pull request merged**
