### PR TITLE
Bump dependencies with npm audit fix

### PR DESCRIPTION
**Pull request by HonkingGoose**
Running `npm audit` gives a lot of warnings.
I ran `npm audit fix` locally, and tested the page-build on `localhost`, and I think it all looks/functions OK.

I don't know if these changes will break the production build though, or cause issues with hosting it on GitHub.

@deniszholob Please check on your end if the build functions as expected. :smile:

---

Edit: I noticed there is no Netlify preview anymore for pull-requests.

### CODE REVIEW

**Comment by deniszholob** [comment]
Yeah netlify is gone now, i was using their free tier, but they started wanting a creditcard on file, and after some time they locked me out, so i ditched them, and am able to use github-pages, tho it was nice to see a deployment preview... oh well :(

npm audit always complains, i usually just wait until i update the angular version, idk.... i really hate messing with dependencies and versions, something always breaks the build....

**Comment by HonkingGoose** [comment]
> i really hate messing with dependencies and versions, something always breaks the build....

What kind of things break then? Is is just that the expected data from the data files is not loaded correctly, or is it layout/rendering issues in the browser?

I could maybe write some tests, so that we have smoke tests for major breakage of the build.
I noticed there are some typescript files that do calculations, I could write tests to check if those calculations are done right.
And browser side tests are also getting easier to do.

So if you want, I could try creating some tests for the project. And even better: with GitHub Actions, we can run those tests on every push and pull-request to `master`. So that you could know immediately if things are broken.

What kind of things would you like tested first, what kind of tests, when they pass, would give you the confidence to deploy to the live site?

**Comment by deniszholob** [comment]
Oh no, the builds have the potential to break when you start messing with versions. The content has nothing to do with that im not worried on that front.
Idk, id rather not mess with that too often, just for the sake of updating. If it works why "fix" it?

**Comment by HonkingGoose** [comment]
> Oh no, the builds have the potential to break when you start messing with versions.
I agree, if the build breaks when you change a minor version, I would not change a thing too!

At the end of the day, it's your project, you can call the shots on how you want to run it.
I'll leave it up to you then as an when you want to update the project, and will stop badgering you about it. 😄

**Pull request closed without merging**
