### PR TITLE
0.17 Belt speed #96

### PR DESCRIPTION
**Pull request by HonkingGoose**
This is a cleaner merge I guess, because it doesn't have my branch from my own repository in it.

### CODE REVIEW

**Comment by deniszholob** [comment]
Thanks for the initiative!, let me get the 0.16 and 0.17 branches set up to build and deploy, then ill target the 0.17 branch for this pr.

Not sure why there are 3 different commits shown though and no changes.

Gunna blow away the current 0.16 0.17 branches because they arnt auto deploying, look for new ones to base your code from in like 5 min

**Comment by HonkingGoose** [comment]
Okay I'll wait on the 0.17 branch on your repository then, so I can help on that.

Do you have any specific thing you want to have me do on your 0.17 branch? So we aren't duplicating effort.

**Comment by HonkingGoose** [comment]
I must have messed something up when I deleted the previous branch on my repo. 

I'll try changing the belt speeds on your 0.17 branch, when you have that ready... :+1:

**Comment by deniszholob** [comment]
@HonkingGoose alright i think i have the branches set up
You should be able to check out the 0.17 branch and make a new fix branch on top of it
Then when you create a PR target that 0.17 branch instead of master.
When all of the 0.17 changes are done, ill merge the entire 0.17 branch into master.

https://factoriocheatsheet.com/
https://v016.factoriocheatsheet.com/
https://v017.factoriocheatsheet.com/

I got PR builds going too, if you click the "Details" on the "deploy/netlify" check you will be able to see the live deployment :P

**Comment by HonkingGoose** [comment]
@deniszholob Okay I'll target your 0.17 branch for my pull-requests then.

I'll see if I can assign myself to the belt issue then.

**Pull request closed without merging**
