### PR TITLE
Adding sw.js for offline/optimized images

### PR DESCRIPTION
**Pull request by dalanmiller**
Enables running the site offline and intelligently caches `json|png|jpeg|css` for faster reloads.

### CODE REVIEW

**Comment by deniszholob** [comment]
Something i wanted to do myself, but havnt got around to learning yet, thanks for the contribution.
I wont be able to properly look at this for at least a week or so, bear with me.

**Comment by dalanmiller** [comment]
No worries, service workers are a bit hard/janky to test properly using `ng
serve` FYI.

Love the site and use it frequently! Reasoning for this was I used to play
a lot of Factorio on my commute and not remembering to load the cheat sheet
before leaving WiFi was a bummer!

**Comment by dalanmiller** [comment]
Bump 👋

**Comment by deniszholob** [comment]
Thanks for the contribution and getting me started in this!
I tried using your code, but something errored out, so i ended up using angular's navite pwa support instead.

**Pull request closed without merging**
